### ISSUE TITLE
403 Forbidden error when running config.

### ISSUE THREAD

**Issue by jmclear** [cognitive-catalyst/WA-Testing-Tool#133]
Hi, I'm working with a client who is unable to run the config using a Windows 10 machine, I am able to do it using a macbook but he can't. He also can't use python3 so using py -3 instead.

PS C:\Users\UI521108\Desktop\WA-Testing-Tool-master> py -3 run.py -c config.ini

ERROR:root:Forbidden

Traceback (most recent call last):

  File "C:\Users\UI521108\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ibm_cloud_sdk_core\base_service.py", line 156, in send

    raise ApiException(

ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

Traceback (most recent call last):

  File "run.py", line 584, in <module>

    func(ARGS)

  File "run.py", line 471, in func

    list_workspaces(iam_apikey, version, url)

  File "run.py", line 84, in list_workspaces

    return c.list_workspaces()

  File "C:\Users\UI521108\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ibm_watson\assistant_v1.py", line 231, in list_workspaces

    response = self.send(request)

  File "C:\Users\UI521108\AppData\Local\Programs\Python\Python38-32\lib\site-packages\ibm_cloud_sdk_core\base_service.py", line 156, in send

    raise ApiException(

ibm_cloud_sdk_core.api_exception.ApiException: Error: Forbidden, Code: 403

**Comment by andrewrfreed** [comment]
The most likely cause is a mismatch between the apikey and the url.

The default url in the config file matches the US-South configuration, if you have deployed in a different region you'll need to update the url.

**Comment by jmclear** [comment]
That was it, thanks!
