### ISSUE TITLE
RuntimeError: Fail to train [,0,,, ,1,] fold workspace

### ISSUE THREAD

**Issue by victorpovar** [cognitive-catalyst/WA-Testing-Tool#138]
`py run.py -c config.ini > output.txt

Traceback (most recent call last):

  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\groupby.py", line 735, in apply

    result = self._python_apply_general(f)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\groupby.py", line 751, in _python_apply_general

    keys, values, mutated = self.grouper.apply(f, self._selected_obj, self.axis)

  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\ops.py", line 171, in apply

    result_values, mutated = splitter.fast_apply(f, group_keys)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\ops.py", line 925, in fast_apply

Traceback (most recent call last):

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\groupby.py", line 735, in apply

    return libreduction.apply_frame_axis0(sdata, f, names, starts, ends)

    result = self._python_apply_general(f)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\groupby.py", line 751, in _python_apply_general

  File "pandas\_libs\reduction.pyx", line 505, in pandas._libs.reduction.apply_frame_axis0

    keys, values, mutated = self.grouper.apply(f, self._selected_obj, self.axis)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\ops.py", line 171, in apply

TypeError: copy() takes no keyword arguments

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "C:\Users\xxxxxx\WA-Testing-Tool\utils\trainConversation.py", line 244, in <module>

    result_values, mutated = splitter.fast_apply(f, group_keys)

    func(ARGS)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\ops.py", line 925, in fast_apply

  File "C:\Users\xxxxxx\WA-Testing-Tool\utils\trainConversation.py", line 135, in func

    return libreduction.apply_frame_axis0(sdata, f, names, starts, ends)

    intent_df = pd.read_csv(args.intentfile, quoting=csv.QUOTE_ALL,

  File "pandas\_libs\reduction.pyx", line 505, in pandas._libs.reduction.apply_frame_axis0

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\groupby.py", line 746, in apply

TypeError: copy() takes no keyword arguments

    return self._python_apply_general(f)

 

During handling of the above exception, another exception occurred:

 

Traceback (most recent call last):

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\groupby.py", line 751, in _python_apply_general

  File "C:\Users\xxxxxx\WA-Testing-Tool\utils\trainConversation.py", line 244, in <module>

    keys, values, mutated = self.grouper.apply(f, self._selected_obj, self.axis)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\ops.py", line 171, in apply

    func(ARGS)

  File "C:\Users\xxxxxx\WA-Testing-Tool\utils\trainConversation.py", line 135, in func

    result_values, mutated = splitter.fast_apply(f, group_keys)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\ops.py", line 925, in fast_apply

    intent_df = pd.read_csv(args.intentfile, quoting=csv.QUOTE_ALL,

    return libreduction.apply_frame_axis0(sdata, f, names, starts, ends)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\groupby.py", line 746, in apply

  File "pandas\_libs\reduction.pyx", line 505, in pandas._libs.reduction.apply_frame_axis0

    return self._python_apply_general(f)

TypeError: copy() takes no keyword arguments

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\groupby.py", line 751, in _python_apply_general

    keys, values, mutated = self.grouper.apply(f, self._selected_obj, self.axis)

  File "C:\Users\xxxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\ops.py", line 171, in apply

    result_values, mutated = splitter.fast_apply(f, group_keys)

  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pandas\core\groupby\ops.py", line 925, in fast_apply

    return libreduction.apply_frame_axis0(sdata, f, names, starts, ends)

  File "pandas\_libs\reduction.pyx", line 505, in pandas._libs.reduction.apply_frame_axis0

TypeError: copy() takes no keyword arguments

Traceback (most recent call last):

  File "run.py", line 584, in <module>

    func(ARGS)

  File "run.py", line 528, in func

    kfold(fold_num=int(fold_num),

  File "run.py", line 166, in kfold

    raise RuntimeError(

RuntimeError: Fail to train [,0,,, ,1,] fold workspace`

**Comment by victorpovar** [comment]
Per investigation with @andrewrfreed the most likely cause of the above error is in the latest major release of the pandas library, the users who experienced the above issue had pandas version of 1.0.0 instead of 0.25.x. This hypothesis needs to be confirmed and the 'requirements.txt' file may need to be updated to lock down the older version of the pandas library.

**Comment by alesyira** [comment]
updating requirements.txt to pandas==0.25 followed by 

> pip3 install --upgrade -r requirements.txt
 
worked for me and I was able to run 

> python3 run.py -c config.ini

 successfully afterwards.  Thanks!  :)

**Comment by andrewrfreed** [comment]
As suggested this is in fact a bug in the released Pandas 1.0.0 and has been fixed in the Pandas development stream but there is not a versioned bundle with the fix - you have to install Pandas 1.0.x from source.

The most prudent workaround seems to be limiting to an earlier pandas (ex: 0.25) for now and removing that restriction when Pandas releases a new 1.0.1 (or similar) bundle in pip.

```
afreed [~/WA-Testing-Tool]$ pip install git+ssh://git@github.com/pandas-dev/pandas.git@1.0.x
Collecting git+ssh://****@github.com/pandas-dev/pandas.git@1.0.x
  Cloning ssh://****@github.com/pandas-dev/pandas.git (to revision 1.0.x) to /private/var/folders/fh/s9j9chmd1hsf5nlwqld6bldh0000gn/T/pip-req-build-010_re23
  Running command git clone -q 'ssh://****@github.com/pandas-dev/pandas.git' /private/var/folders/fh/s9j9chmd1hsf5nlwqld6bldh0000gn/T/pip-req-build-010_re23
  Running command git checkout -b 1.0.x --track origin/1.0.x
  Switched to a new branch '1.0.x'
  Branch '1.0.x' set up to track remote branch '1.0.x' from 'origin'.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas==1.0.1) (2019.2)
Requirement already satisfied: numpy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas==1.0.1) (1.18.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas==1.0.1) (2.8.0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas==1.0.1) (1.12.0)
Building wheels for collected packages: pandas
  Building wheel for pandas (PEP 517) ... done
  Created wheel for pandas: filename=pandas-1.0.1-cp37-cp37m-macosx_10_9_x86_64.whl size=9968461 sha256=2bfd60cc94149ae7da52baf86ade9642b70ddad99f9bf3f54bca6f65e6a47275
  Stored in directory: /private/var/folders/fh/s9j9chmd1hsf5nlwqld6bldh0000gn/T/pip-ephem-wheel-cache-r8lxc3fr/wheels/bc/cb/7a/1adb16c31ce1da227293e800844e6bf391d603bc9eea5f9e1c
Successfully built pandas
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 1.0.0
    Uninstalling pandas-1.0.0:
      Successfully uninstalled pandas-1.0.0
Successfully installed pandas-1.0.1
```

I was able to successfully run kfolds with this version of pandas installed from source.

**Comment by andrewrfreed** [comment]
More on Pandas bug here: https://stackoverflow.com/questions/60002936/typeerror-copy-takes-no-keyword-arguments-in-python-3-x

**Comment by andrewrfreed** [comment]
Only pandas 1.0.0 is broken.  I tested with pandas 1.0.1 and it works.

The pandas requirement (>=0.21) will install a non-1.0.0 version since 1.0.1 is out.
