### ISSUE TITLE
Tool failing with the SSL: [CERTIFICATE_VERIFY_FAILED] message

### ISSUE THREAD

**Issue by victorpovar** [cognitive-catalyst/WA-Testing-Tool#38]
The tool is failing with the following message while running on MacOS:
```
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host gateway.watsonplatform.net:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/victorpovar/Desktop/WA-Testing-Tool-master/utils/testConversation.py", line 194, in <module>
    func(ARGS)
  File "/Users/victorpovar/Desktop/WA-Testing-Tool-master/utils/testConversation.py", line 131, in func
    loop.run_until_complete(asyncio.gather(*tasks))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/Users/victorpovar/Desktop/WA-Testing-Tool-master/utils/testConversation.py", line 72, in fill_df
    'alternate_intents': True}, url, sem)
RETRY
  File "/Users/victorpovar/Desktop/WA-Testing-Tool-master/utils/testConversation.py", line 55, in post
3
    print(response.status)
RETRY
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by victorpovar** [comment]
The issue was resolved by following the instructions in this post: https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c

**Comment by andrewrfreed** [comment]
Thank you for documenting this Victor - I just ran into this with a brand new Mac install!
